services:
  - type: web
    name: devpulse-api
    runtime: python
    region: oregon
    plan: free

    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT

    healthCheckPath: /health

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8

      - key: ENVIRONMENT
        value: production

      - key: DATABASE_URL
        fromDatabase:
          name: devpulse-db
          property: connectionString

      - key: SECRET_KEY
        generateValue: true

      - key: CORS_ORIGINS
        value: https://abhishekcodee.github.io

databases:
  - name: devpulse-db
    plan: free
    region: oregon
